// Offline support. Generated by build/build.py from src/sw.js: edit that, not sw.js.
// Cache first: every page and script is saved on the device when this version installs, and served
// from there instantly, online or off. A new version of the site arrives as a new worker, which saves
// the new files together and then takes over, so a page and its scripts always match.
const VERSION = "a3bf29cfdb";
const CACHE = "japanese-" + VERSION;
const FILES = ["./","./index.html","./manifest.webmanifest","./assets/icons/icon-192.png","./assets/icons/icon-512.png","./assets/icons/icon-180.png","./assets/common.js","./index.html","./assets/search-index.js","./kanji/master-kanji-shapes.html","./kanji/kanji-by-situation.html","./words/phrasebook.html","./words/sentence-builder.html","./kanji/learn.html","./kanji/learn-n5-n4.html","./words/vocabulary.html","./kana/kana-sounds.html","./kana/kana-words.html","./kana/katakana-words.html","./words/patterns.html","./words/grammar.html","./assets/common.js?v=e09031b852","./assets/search-index.js?v=b988aede29"];
self.addEventListener("install", e => {
  // one by one, so one failure can't stop the rest from being saved
  e.waitUntil(caches.open(CACHE).then(c => Promise.all(FILES.map(f => c.add(new Request(f, { cache: "reload" })).catch(() => null)))).then(() => self.skipWaiting()));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith("japanese-") && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
const scope = new URL(self.registration.scope);
async function lookup(c, req, url) {
  let hit = await c.match(req);                                   // exact: versioned scripts, icons
  if (hit) return hit;
  const page = req.mode === "navigate" || url.pathname.endsWith(".html") || url.pathname.endsWith("/");
  if (!page) return null;
  hit = await c.match(req, { ignoreSearch: true });              // ?from=... on a page link
  if (hit) return hit;
  if (url.pathname.endsWith("/")) hit = await c.match(new URL(url.pathname + "index.html", url.origin).href);
  return hit || null;
}
self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  const font = /fonts\.(googleapis|gstatic)\.com$/.test(url.hostname);
  if (url.origin !== location.origin && !font) return;
  if (font) {   // saved fonts come straight back; an unsaved one gets 1.5 seconds, never a long offline wait
    e.respondWith((async () => {
      const c = await caches.open(CACHE);
      const hit = await c.match(req);
      if (hit) return hit;
      try {
        const res = await Promise.race([fetch(req), new Promise((_, no) => setTimeout(() => no(new Error("slow")), 1500))]);
        if (res && (res.ok || res.type === "opaque")) c.put(req, res.clone());
        return res;
      } catch (err) { return new Response("", { status: 504 }); }
    })());
    return;
  }
  e.respondWith((async () => {
    const c = await caches.open(CACHE);
    const hit = await lookup(c, req, url);
    if (hit) return hit;                                          // instant, and works offline
    try {
      const res = await fetch(req);
      if (res && (res.ok || res.type === "opaque")) c.put(req, res.clone());
      return res;
    } catch (err) {
      if (req.mode === "navigate") { const home = await c.match(new URL("index.html", scope).href); if (home) return home; }
      return Response.error();
    }
  })());
});
