// Offline support. Generated by build/build.py from src/sw.js: edit that, not sw.js.
// Network first: when online you always get the latest pages and scripts together;
// the cache is only used when there's no connection.
const VERSION = "__VERSION__";
const CACHE = "japanese-" + VERSION;
const FILES = __FILES__;
self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith("japanese-") && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  const font = /fonts\.(googleapis|gstatic)\.com$/.test(url.hostname);
  if (url.origin !== location.origin && !font) return;
  if (font) {   // fonts never change: cache first
    e.respondWith(caches.open(CACHE).then(async c => (await c.match(req)) || fetch(req).then(r => { c.put(req, r.clone()); return r; })));
    return;
  }
  e.respondWith(
    fetch(req, { cache: "no-cache" })
      .then(res => { if (res && res.ok) caches.open(CACHE).then(c => c.put(req, res.clone())); return res; })
      .catch(() => caches.open(CACHE).then(c => c.match(req, { ignoreSearch: true })))
  );
});
